name: basic_lpips
work_dir: "./work_dir/"

resolution: 512
high_resolution: 2048

model:
  generator:
    _type: UNet
    in_channels: 3
    out_channels: 3

optimizer:
  lr: 1e-4

loss:
  perceptual:
    layers:
      conv1_2: 0.384615 # 1 / 2.6
      conv2_2: 0.208333 # 1 / 4.8
      conv3_2: 0.270270 # 1 / 3.7
      conv4_2: 0.178571 # 1 / 5.6
      conv5_2: 6.666666 # 10 / 1.5
    criterion: L1
  weight:
    flare:
      ffl: 100
      lpips: 1
    scene:
      l1: 1
      lpips: 1

augment:
  way: add_flare_paper
  add_flare:
    resize_scale: [0.5, 1.5]
    apply_affine: True
    apply_random_white_balance: False
    resolution: 512
    flare_max_gain: 2.0
    noise_strength: 0.01
  add_flare_paper:
    apply_affine: True
    resolution:  512
    flare_max_gain: 10.0
    noise_strength: 0.01


train:
  num_epoch: 50
  dataset:
    folders_a:
      - "/home/dancer/dataset/Flickr/synthetic"
    folders_b:
      - "/home/dancer/dataset/lens-flare"
    transform:
      - ToTensor
    recursive: True
    return_image_path: False
  dataloader:
    batch_size: 2
    num_workers: 2
    prefetch_factor: 1
    shuffle: True
    drop_last: True
    pin_memory: True

log:
  evaluate:
    interval_epoch: 1
  checkpoint:
    interval_epoch: 2
  tensorboard:
    scalar_interval: 100
    image_interval: 2000

evaluate:
  dataloader:
    batch_size: 1
  dataset:
    folders_a:
      - "/home/dancer/dataset/test_data/paper20/input"
    folders_b:
      - "/home/dancer/dataset/test_data/paper20/ground_truth"
    transform:
      - ToTensor
      - Resize:
          size: 512
    recursive: True
    return_image_path: True

generate:
  dataloader:
    batch_size: 1
  dataset:
    folders: "/home/dancer/dataset/test_data/paper20/input"
    transform:
      - ToTensor
      - Resize:
          size: 512
    recursive: True
    return_image_path: True