name: original_paper
work_dir: "./work_dir/"

model:
  generator:
    in_channels: 3
    out_channels: 3

optimizer:
  lr: 1e-4

loss:
  perceptual:
    layers:
      conv1_2: 0.384615 # 1 / 2.6
      conv2_2: 0.208333 # 1 / 4.8
      conv3_2: 0.270270 # 1 / 3.7
      conv4_2: 0.178571 # 1 / 5.6
      conv5_2: 6.666666 # 10 / 1.5
    criterion: L1
  weight:
    flare:
      l1: 1
      perceptual: 1
    scene:
      l1: 1
      lpips: 1


train:
  num_epoch: 50
  dataset:
    folders_a:
      - "/home/dancer/dataset/Flickr/synthetic"
    folders_b:
      - "/home/dancer/dataset/lens-flare"
    transform:
      - ToTensor
    recursive: True
    return_image_path: False
  dataloader:
    batch_size: 2
    num_workers: 2
    prefetch_factor: 1
    shuffle: True
    drop_last: True
    pin_memory: True

log:
  checkpoint:
    interval_epoch: 2
  tensorboard:
    scalar_interval: 100
    image_interval: 2000
